allow management bind address to be specified seperately
closes #2

diff --git a/cont-init.d/020-wildfly-bind-address b/cont-init.d/020-wildfly-bind-address
--- a/cont-init.d/020-wildfly-bind-address
+++ b/cont-init.d/020-wildfly-bind-address
@@ -1,27 +1,40 @@
 #!/usr/bin/with-contenv /bin/sh
 
-intf=${WILDFLY_BIND_INTERFACE:-eth0}
+function intf2addr() {
+  intf=$1
+  if [ "$intf" == "any" ]; then
+    addr=0.0.0.0
+  elif [ "$intf" == "lo" ]; then
+    addr=127.0.0.1
+  elif ip link list dev "$intf" >/dev/null 2>&1; then
+    addr=$(ip address list scope global dev ${intf} \
+              | grep "inet" \
+              | awk '{print $2}' \
+              | cut -f1 -d'/')
+  else
+    addr=$(ip route list $intf | awk '{print $NF}')
+  fi
 
-if [ "$intf" == "any" ]; then
-  addr=0.0.0.0
-elif ip link list dev "$intf" >/dev/null 2>&1; then
-  echo "it's an interface"
-  addr=$(ip address list scope global dev ${intf} \
-            | grep "inet" \
-            | awk '{print $2}' \
-            | cut -f1 -d'/')
-else
-  addr=$(ip route list $intf | awk '{print $NF}')
-fi
+  if [ -z "$addr" ]; then
+    echo "WARNING: cannot determine interface address for '$intf'" >&2
+    echo "WARNING: binding to all interfaces as a fallback" >&2
+    addr=0.0.0.0
+  fi
 
-if [ -z "$addr" ]; then
-  echo "WARNING: cannot determine interface address for '$intf'" >&2
-  echo "WARNING: binding to all interfaces as a fallback" >&2
-  addr=0.0.0.0
-fi
+  echo $addr
+}
 
-echo "interface address is $addr"
-echo $addr > ${WILDFLY_BIND_ADDRESS}
+bind_addr=$(intf2addr ${WILDFLY_BIND_INTERFACE:-eth0})
+echo $bind_addr > ${WILDFLY_BIND_ADDRESS}
 chown ${WILDFLY_USER}:${WILDFLY_USER} ${WILDFLY_BIND_ADDRESS}
 echo "bind address is $(cat ${WILDFLY_BIND_ADDRESS})"
 
+if [ -z "${WILDFLY_MGMT_BIND_INTERFACE}" ]; then
+  echo $bind_addr > ${WILDFLY_MGMT_BIND_ADDRESS}
+  chown ${WILDFLY_USER}:${WILDFLY_USER} ${WILDFLY_MGMT_BIND_ADDRESS}
+else
+  mgmt_bind_addr=$(intf2addr "${WILDFLY_MGMT_BIND_INTERFACE}")
+  echo $mgmt_bind_addr > ${WILDFLY_MGMT_BIND_ADDRESS}
+  chown ${WILDFLY_USER}:${WILDFLY_USER} ${WILDFLY_MGMT_BIND_ADDRESS}
+  echo "management bind address is $(cat ${WILDFLY_MGMT_BIND_ADDRESS})"
+fi  
