allow for read-only root

diff --git a/cont-init.d/150-wildfly-config b/cont-init.d/150-wildfly-config
--- a/cont-init.d/150-wildfly-config
+++ b/cont-init.d/150-wildfly-config
@@ -1,10 +1,23 @@
-#!/bin/sh
+#!/usr/bin/with-contenv /bin/sh
 
-CONFIG_DIR=/etc/wildfly/config.d
+CONFIG_LOCK=/var/run/wildfly-config.lock
+CONFIG_DIR=${WILDFLY_CONFIG_DIR:-/etc/wildfly/config.d}
 ME="[wildfly/config.d]"
 CLI=/apps/wildfly/bin/jboss-cli.sh
-CLI_SCRIPT=$(mktemp)
 
+if [ -f "$CONFIG_LOCK" ]; then
+  echo "configuration has already been applied"
+  exit
+fi
+
+if [ ! -d "${CONFIG_DIR}" ]; then
+  echo "${CONFIG_DIR}: not found" >&2
+  exit 1
+fi
+
+echo "applying configuration in ${CONFIG_DIR}"
+
+CLI_SCRIPT=$(mktemp)
 echo "embed-server" > $CLI_SCRIPT
 
 count=0
@@ -22,3 +35,4 @@ if [ $count -ne 0 ]; then
 fi
 
 rm $CLI_SCRIPT
+touch $CONFIG_LOCK
